# build stage
FROM node:current-alpine as build-stage
WORKDIR /app
COPY . .
# Declara e expõe o ARG para o Vite
ARG VITE_API_URL
ENV VITE_API_URL=$VITE_API_URL
RUN npm install --legacy-peer-deps
RUN npm run build

# production stage
FROM nginx:stable-alpine as production
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build-stage /app/dist/ /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
