name: NodeJS with Vite

on:
  push:
    branches: 
      - develop
      - main

env:
  IMAGE_NAME: ${{ github.event.repository.name }}
  IMAGE_TAG: v${{ github.run_number }}

jobs:
  quality:
    name: Quality Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Lint test
        run: |
          npm install
          npm audit fix

  sonar:
    name: SonarQube
    needs: quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      
      - uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
